services:
  db:
    image: postgres:latest
    container_name: pact_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: pact_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
